version: "3.9"

services:
  postgres:
    container_name: auth_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data

volumes:
  auth_db_data:
    name: auth_db_data
