auth:
  google:
    google-auth-url: https://www.googleapis.com
  yandex:
    yandex-auth-url: https://login.yandex.ru

jwt:
  expire-time-in-seconds: 3600
  refresh-token-expire-time-in-days: 7

spring:
  application:
    name: AuthService
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: false
            tablePrefix: QRTZ_
            clusterCheckinInterval: 5000
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true
      auto-startup: false

server:
  port: 8080