auth:
  google:
    google-auth-url: https://www.googleapis.com

jwt:
  expire-time-in-seconds: 900
  refresh-token-expire-time-in-days: 7

spring:
  application:
    name: AuthService
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080